version: '3.8'

services:

  nginx:
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/app
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
  
  php:
    build: .
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  mysqldata: